name: Core Python Tests

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/core-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/core-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.12']
      fail-fast: false # Don't cancel other Python version tests if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install Required System Libraries for Numba/llvmlite
        run: sudo apt-get update && sudo apt-get install -y libgcc-12-dev

      - name: Install dependencies with uv sync
        run: uv sync --all-extras

      - name: Install project package
        run: uv run uv pip install --no-deps .

      # --- Test Steps ---
      - name: Step 1 - Run Main Import Test (test_imports.py)
        run: uv run python -m unittest tests/test_imports.py

      - name: Step 2 - Run Module Import Tests
        run: uv run python -m unittest discover -s tests -p "test_*_imports.py"

      - name: Step 3 - Run Unit/Functional Tests (quick tests)
        run: uv run python tests/run_quick_tests.py